#!/bin/sh
echo git-out-all
set -e

#trigger error early if not in a repo
git remote >/dev/null
ACTUALBRANCH='git branch | grep "*" | cut -b 3-'

#save repo name
REMOTE=`git remote | head -1`

#pull last remotes
git fetch $REMOTE

#name guessing
for branch in `git branch | cut -b 3-`;
do
	git checkout $branch > /dev/null
	#go for command
	OUT=`git log $branch..$REMOTE/$branch`
	#do output only if differences
	if [ ${#OUT} != 0 ];
	then
	        echo Assuming remote branch "$REMOTE/$branch"
		echo "--"
	        git log $branch..$REMOTE/$branch
		echo "--"
	else
		echo "--"
			echo Nothing outgoing.
		echo "--"
	fi
	echo " "
done
git checkout $ACTUALBRANCH
